--- 
- name: make knife directory
  file: path=~/.chef state=directory

- name: copy knife setup script
  copy: src=knife.sh dest=/tmp/knife.sh mode=0755

- name: check if knife is already configured
  command: ls ~/.chef
  register: result

- name: run knife setup script
  shell: /tmp/knife.sh >> knife.txt chdir=/tmp/
  when: result.stdout.find('root') == -1

- name: replace knife config file
  copy: src=knife.rb dest=/root/.chef/knife.rb mode=0644
