---

- name: restart compass service
  service: name={{ item }} state=restarted enabled=yes
  with_items:
    - compass-celeryd
    - compass-progress-updated

- name: restart http service
  service: name=httpd state=restarted enabled=yes
